## NumPy

## SEED

In [1]:
import numpy as np

## Broadcasting

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
l1 = [0,1,2,3,4,5,6,7,8,9]

In [7]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
l1[1]/10

0.1

In [9]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [12]:
arr[arr>5]

array([6, 7, 8, 9])

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1 = arr[0:6]

In [15]:
arr1

array([0, 1, 2, 3, 4, 5])

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[:5]

array([0, 1, 2, 3, 4])

In [18]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [19]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr1[:]

array([0, 1, 2, 3, 4, 5])

In [21]:
arr1[:] = 555

In [22]:
arr1

array([555, 555, 555, 555, 555, 555])

In [23]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

##### Copy of an Array

In [24]:
arr2 = arr.copy()

In [25]:
arr2

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

In [26]:
arr2[:]=1000

In [27]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [28]:
arr

array([555, 555, 555, 555, 555, 555,   6,   7,   8,   9])

### Python List Vs Numpy Array

In [29]:
size = 1000
x = range(size)
y = range(size)

In [30]:
%%timeit
[x[i]*y[i] for i in range(size)]


224 µs ± 3.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [31]:
x1 = np.arange(size)
y1 = np.arange(size)

In [32]:
%%timeit
x1*y1

1.29 µs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Insert

In [33]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
b1 =np.insert(b,1,[15,16,17],axis=0)

In [35]:
np.insert(b,1,[15,16,17],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [36]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### Matrix

In [39]:
x = np.matrix('1,2,3;4,5,6;7,8,9')

In [40]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
x[2,1] = -7

In [42]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr[2:1] = -7

In [47]:
np.insert(arr,2,2)

array([1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x*x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [49]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [50]:
arr@arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Storage in File

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.savetxt('a.txt',arr)

In [54]:
np.savetxt('a.txt',arr,delimiter=',')

In [55]:
np.loadtxt('a.txt',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
np.save('data.npy',arr)

In [57]:
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a = np.arange(10)

In [59]:
np.savez('both.npz',arr,a)

In [60]:
z = np.load('both.npz')

In [61]:
z.files

['arr_0', 'arr_1']

In [63]:
z[z.files[0]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
import pandas as pd
import numpy as np

### Using list

In [66]:
my_list = [100,200,300,400,500]

In [67]:
x = pd.Series(my_list,index=['A','B','C','D','E'])

In [69]:
x

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [70]:
type(x)

pandas.core.series.Series

### Using NumPy array

In [71]:
arr = np.array(my_list)

In [72]:
arr

array([100, 200, 300, 400, 500])

In [73]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [74]:
pd.Series(arr,'A B C D E'.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

### Using Dictionaries

In [75]:
dict1 = {'A':100,'B':200,'C':300}

In [76]:
z1 = pd.Series(dict1)

In [77]:
z1

A    100
B    200
C    300
dtype: int64

In [78]:
z2 = pd.Series([10,20,30,40],'A B C D'.split())

In [79]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [80]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

### Slicing in Series

#### z2

In [81]:
z2[0:2]

A    10
B    20
dtype: int64

In [82]:
z2['A':'C']

A    10
B    20
C    30
dtype: int64

### .loc & .iloc functions

In [83]:
z2.loc['A':'C']

A    10
B    20
C    30
dtype: int64

In [84]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [85]:
z = pd.Series({100:'a',200:'b',300:'c'})

In [86]:
z

100    a
200    b
300    c
dtype: object

In [87]:
z.iloc[0]

'a'

#### Operations

In [88]:
z1

A    100
B    200
C    300
dtype: int64

In [89]:
z1>100

A    False
B     True
C     True
dtype: bool

In [90]:
z1<200

A     True
B    False
C    False
dtype: bool

### Broadcasting

In [91]:
z1+300

A    400
B    500
C    600
dtype: int64

### Ordering

In [92]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [93]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [94]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [95]:
z2.sort_values(ascending=False,inplace=True)

In [96]:
z2

D    40
C    30
B    20
A    10
dtype: int64

### Aggregation on Series

In [97]:
z2

D    40
C    30
B    20
A    10
dtype: int64

In [98]:
z2.min()

10

In [99]:
z2.max()

40

In [100]:
z2.idxmax()

'D'

### Data Frame

In [101]:
rand_mat = np.random.randn(5,4)

In [102]:
rand_mat

array([[-2.52110605, -1.66979289,  2.27024836, -0.74786802],
       [-1.70636719, -0.82204123, -3.04858065,  0.39535271],
       [-1.77304037, -0.51391695, -0.29804063,  0.09080409],
       [-0.01750726,  2.69331089,  0.54656514,  0.43237423],
       [ 1.42053988, -0.535691  , -0.31612516,  0.33951389]])

In [103]:
df = pd.DataFrame(data=rand_mat, index = 'A B C D E'.split(),columns = 'W X Y Z'.split())

In [104]:
df

W         X         Y         Z
A -2.521106 -1.669793  2.270248 -0.747868
B -1.706367 -0.822041 -3.048581  0.395353
C -1.773040 -0.513917 -0.298041  0.090804
D -0.017507  2.693311  0.546565  0.432374
E  1.420540 -0.535691 -0.316125  0.339514

In [105]:
type(df)

pandas.core.frame.DataFrame

In [106]:
df['W']

A   -2.521106
B   -1.706367
C   -1.773040
D   -0.017507
E    1.420540
Name: W, dtype: float64

In [107]:
type(df['W'])

pandas.core.series.Series

## Selection & Indexing

In [108]:
df.loc['A']

W   -2.521106
X   -1.669793
Y    2.270248
Z   -0.747868
Name: A, dtype: float64

In [109]:
df[['W','Z']]

W         Z
A -2.521106 -0.747868
B -1.706367  0.395353
C -1.773040  0.090804
D -0.017507  0.432374
E  1.420540  0.339514

#### Add a New Column

In [110]:
df['New'] = df['W'] + df['Y']

In [111]:
df

W         X         Y         Z       New
A -2.521106 -1.669793  2.270248 -0.747868 -0.250858
B -1.706367 -0.822041 -3.048581  0.395353 -4.754948
C -1.773040 -0.513917 -0.298041  0.090804 -2.071081
D -0.017507  2.693311  0.546565  0.432374  0.529058
E  1.420540 -0.535691 -0.316125  0.339514  1.104415

In [112]:
df.drop('New',axis=1)

W         X         Y         Z
A -2.521106 -1.669793  2.270248 -0.747868
B -1.706367 -0.822041 -3.048581  0.395353
C -1.773040 -0.513917 -0.298041  0.090804
D -0.017507  2.693311  0.546565  0.432374
E  1.420540 -0.535691 -0.316125  0.339514

In [113]:
df

W         X         Y         Z       New
A -2.521106 -1.669793  2.270248 -0.747868 -0.250858
B -1.706367 -0.822041 -3.048581  0.395353 -4.754948
C -1.773040 -0.513917 -0.298041  0.090804 -2.071081
D -0.017507  2.693311  0.546565  0.432374  0.529058
E  1.420540 -0.535691 -0.316125  0.339514  1.104415

In [114]:
df.drop('New',axis=1,inplace=True)

In [115]:
df

W         X         Y         Z
A -2.521106 -1.669793  2.270248 -0.747868
B -1.706367 -0.822041 -3.048581  0.395353
C -1.773040 -0.513917 -0.298041  0.090804
D -0.017507  2.693311  0.546565  0.432374
E  1.420540 -0.535691 -0.316125  0.339514

#### Add a New Row

In [116]:
df.loc['F'] = df.loc['A'] + df.loc['C']

In [117]:
df

W         X         Y         Z
A -2.521106 -1.669793  2.270248 -0.747868
B -1.706367 -0.822041 -3.048581  0.395353
C -1.773040 -0.513917 -0.298041  0.090804
D -0.017507  2.693311  0.546565  0.432374
E  1.420540 -0.535691 -0.316125  0.339514
F -4.294146 -2.183710  1.972208 -0.657064

In [118]:
df.drop('F',axis=0,inplace=True)

In [119]:
df

W         X         Y         Z
A -2.521106 -1.669793  2.270248 -0.747868
B -1.706367 -0.822041 -3.048581  0.395353
C -1.773040 -0.513917 -0.298041  0.090804
D -0.017507  2.693311  0.546565  0.432374
E  1.420540 -0.535691 -0.316125  0.339514

In [120]:
df['X']['C']

-0.5139169451594119

In [121]:
df.loc['C']['X']

-0.5139169451594119

### Data Input & Output

In [124]:
pd.read_csv('electronic-card-transactions-march-2024-csv-tables.csv')

Series_reference   Period  Data_value Suppressed STATUS    UNITS  \
0           ECTA.S19A1  2001.03      2462.5        NaN      F  Dollars   
1           ECTA.S19A1  2002.03     17177.2        NaN      F  Dollars   
2           ECTA.S19A1  2003.03     22530.5        NaN      F  Dollars   
3           ECTA.S19A1  2004.03     28005.1        NaN      F  Dollars   
4           ECTA.S19A1  2005.03     30629.6        NaN      F  Dollars   
...                ...      ...         ...        ...    ...      ...   
20356       ECTQ.S4AXP  2023.03        31.9        NaN      F  Percent   
20357       ECTQ.S4AXP  2023.06        33.0        NaN      F  Percent   
20358       ECTQ.S4AXP  2023.09        33.2        NaN      F  Percent   
20359       ECTQ.S4AXP  2023.12        32.7        NaN      F  Percent   
20360       ECTQ.S4AXP  2024.03        32.0        NaN      F  Percent   

       Magnitude                                        Subject  \
0              6  Electronic Card Transactions (ANZSIC06) - ECT   
1              6  Electronic Card Transactions (ANZSIC06) - ECT   
2              6  Electronic Card Transactions (ANZSIC06) - ECT   
3              6  Electronic Card Transactions (ANZSIC06) - ECT   
4              6  Electronic Card Transactions (ANZSIC06) - ECT   
...          ...                                            ...   
20356          0  Electronic Card Transactions (ANZSIC06) - ECT   
20357          0  Electronic Card Transactions (ANZSIC06) - ECT   
20358          0  Electronic Card Transactions (ANZSIC06) - ECT   
20359          0  Electronic Card Transactions (ANZSIC06) - ECT   
20360          0  Electronic Card Transactions (ANZSIC06) - ECT   

                                                   Group Series_title_1  \
0      Total values - Electronic card transactions A/...         Actual   
1      Total values - Electronic card transactions A/...         Actual   
2      Total values - Electronic card transactions A/...         Actual   
3      Total values - Electronic card transactions A/...         Actual   
4      Total values - Electronic card transactions A/...         Actual   
...                                                  ...            ...   
20356  Electronic card transactions by mean and propo...         Actual   
20357  Electronic card transactions by mean and propo...         Actual   
20358  Electronic card transactions by mean and propo...         Actual   
20359  Electronic card transactions by mean and propo...         Actual   
20360  Electronic card transactions by mean and propo...         Actual   

                                          Series_title_2  Series_title_3  \
0                                   RTS total industries             NaN   
1                                   RTS total industries             NaN   
2                                   RTS total industries             NaN   
3                                   RTS total industries             NaN   
4                                   RTS total industries             NaN   
...                                                  ...             ...   
20356  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20357  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20358  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20359  Debit card usage as a proportion of total ECT ...  Proportion (%)   
20360  Debit card usage as a proportion of total ECT ...  Proportion (%)   

       Series_title_4  Series_title_5  
0                 NaN             NaN  
1                 NaN             NaN  
2                 NaN             NaN  
3                 NaN             NaN  
4                 NaN             NaN  
...               ...             ...  
20356             NaN             NaN  
20357             NaN             NaN  
20358             NaN             NaN  
20359             NaN             NaN  
20360             NaN             NaN  

[20361 rows x 14 

## Statistics Functions

In [125]:
import numpy as np

In [126]:
x = np.array([[1,2,3],[2,4,6],[90,100,50]])

In [127]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [128]:
np.amin(x)

1

In [129]:
np.amax(x)

100

In [130]:
np.amin(x, axis=1)

array([ 1,  2, 50])

In [131]:
np.amin(x, axis=0)

array([1, 2, 3])

In [132]:
np.amax(x, axis=0)

array([ 90, 100,  50])

In [133]:
np.amax(x, axis=1)

array([  3,   6, 100])

In [134]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [135]:
np.average(x)

28.666666666666668

#### Weighted Average

In [136]:
w=[1,2,3]

In [137]:
np.average(x, weights= w, axis=0)

array([45.83333333, 51.66666667, 27.5       ])

In [138]:
np.average(x, weights= w, axis=1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [139]:
np.mean(x)

28.666666666666668

In [140]:
np.mean(x[0])

2.0

In [141]:
np.mean(x[1])

4.0

In [142]:
np.mean(x[2])

80.0

In [143]:
np.mean(x, axis=0)

array([31.        , 35.33333333, 19.66666667])

In [144]:
np.mean(x, axis=1)

array([ 2.,  4., 80.])

In [145]:
np.median(x)

4.0

In [146]:
np.median(x, axis=1)

array([ 2.,  4., 90.])

In [147]:
np.median(x, axis=0)

array([2., 4., 6.])

In [148]:
np.var(x)

1474.888888888889

In [149]:
np.std(x)

38.4042821686448